export const FETCH_IMAGE = 'FETCH_IMAGE';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
